import FWCore.ParameterSet.Config as cms
from DQM.SiPixelPhase1Heterogeneous.siPixelPhase1MonitorTrackSoA_cfi import *
from DQM.SiPixelPhase1Heterogeneous.siPixelPhase1MonitorVertexSoA_cfi import *
from DQM.SiPixelPhase1Heterogeneous.siPixelPhase1MonitorRecHitsSoACPU_cfi import *
from DQM.SiPixelPhase1Heterogeneous.siPixelPhase1MonitorRecHitsSoAGPU_cfi import *

monitorpixelSoASource = cms.Sequence(siPixelPhase1MonitorTrackSoA * siPixelPhase1MonitorVertexSoA * siPixelPhase1MonitorRecHitsSoACPU)
monitorpixelSoAGPU = cms.Sequence(siPixelPhase1MonitorTrackSoA * siPixelPhase1MonitorVertexSoA * siPixelPhase1MonitorRecHitsSoAGPU)

from Configuration.ProcessModifiers.gpu_cff import gpu
gpu.toReplaceWith(monitorpixelSoASource, monitorpixelSoAGPU)

